sites:
  reuters:
      url: "https://www.reuters.com/"
      enabled: false
  latimes:
      url: "https://www.latimes.com/homeless-housing"
      enabled: false
  latimes_keyword:
      url: "https://www.latimes.com"
      enabled: false
  laist:
      url: "https://laist.com/news/housing-homelessness"
      enabled: false
  laist_keyword:
      url: "https://laist.com"
      enabled: false
  theguardian:
      url: "https://www.theguardian.com/us-news/"
      enabled: false
  downtownla:
      url: "https://downtownla.com/"
      enabled: false
  apnews:
      url: "https://apnews.com/"
      enabled: false
  lacity:
      url: "https://lacity.gov/"
      enabled: true
keywords:
    - Unhoused
    - Homelessness
    - Downtown Los Angeles
cutoff_days: 8

driver:
  headless: false