sites:
  reuters:
      url: "https://www.reuters.com/"
      enabled: false
  latimes:
      url: "https://www.latimes.com/homeless-housing"
      enabled: true
  laist:
      url: "https://laist.com/news/housing-homelessness"
      enabled: false
  theguardian:
      url: "https://www.theguardian.com/us-news/"
      enabled: false
  downtownla:
      url: "https://downtownla.com/articles"
      enabled: false
  apnews:
      url: "https://apnews.com/"
      enabled: false
  lacity:
      url: "https://lacity.gov/"
      enabled: false
keywords:
    - Unhoused
    - Homelessness
    - Downtown Los Angeles

driver:
  headless: false